package fr.eni.lokacar.dao;

import org.greenrobot.greendao.annotation.*;

import fr.eni.lokacar.app.App;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "CLIENT".
 */
@Entity
public class Client {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String Nom;

    @NotNull
    private String Prenom;

    @NotNull
    private String Telephone;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Client() {
    }

    public Client(Long id) {
        this.id = id;
    }

    @Generated
    public Client(Long id, String Nom, String Prenom, String Telephone) {
        this.id = id;
        this.Nom = Nom;
        this.Prenom = Prenom;
        this.Telephone = Telephone;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getNom() {
        return Nom;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNom(@NotNull String Nom) {
        this.Nom = Nom;
    }

    @NotNull
    public String getPrenom() {
        return Prenom;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPrenom(@NotNull String Prenom) {
        this.Prenom = Prenom;
    }

    @NotNull
    public String getTelephone() {
        return Telephone;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTelephone(@NotNull String Telephone) {
        this.Telephone = Telephone;
    }

    @Override
    public String toString() {
        return getPrenom().toUpperCase() + " " + getNom().toUpperCase();
    }
}
